export default [
  { name: 'academy' },
  { name: 'bakery' },
  { name: 'barracks' },
  { name: 'brickyard' },
  { name: 'cranny' },
  { name: 'embassy' },
  { name: 'grainmill' },
  { name: 'granary' },
  { name: 'greatbarracks' },
  { name: 'greatstable' },
  { name: 'ironfoundry' },
  { name: 'mainbuilding' },
  { name: 'marketplace' },
  { name: 'palace' },
  { name: 'rallypoint' },
  { name: 'residence' },
  { name: 'sawmill' },
  { name: 'smithy' },
  { name: 'stable' },
  { name: 'stonemason' },
  { name: 'tournamentsquare' },
  { name: 'townhall' },
  { name: 'tradeoffice' },
  { name: 'treasury' },
  { name: 'warehouse' },
  { name: 'workshop' },
]
